FROM python:3.8-slim-buster
USER root
COPY ../requirements.txt requirements.txt
EXPOSE 5002 15001
RUN pip3 install -r requirements.txt
COPY . /app
WORKDIR /app
ENTRYPOINT ["scripts/ss2-local-docker.sh"]