FROM python:3.8-slim-buster
USER root
COPY ../requirements.txt requirements.txt
EXPOSE 5001 15000
RUN pip3 install -r requirements.txt
COPY . /app
WORKDIR /app
ENTRYPOINT ["../scripts/ss1-local-docker.sh"]